package com.example.model

/**
 * State and telemetry data generated by the Hardware Sensor CSPRNG Entropy Service.
 */
data class HardwareSensorEntropyState(
    val isRunning: Boolean = false,
    val sampleCount: Long = 0L,
    val poolEntropyBits: Int = 512,
    val estimatedShannonEntropy: Double = 7.98, // Close to theoretical max 8.0 bits/byte
    val latestHexSeed: String = "",
    val latestRandomBytes64: String = "",
    val activeSensors: List<String> = emptyList(),
    val rawJitterMetric: Float = 0.88f,
    val lastHarvestTimestamp: Long = 0L,
    val totalCyclesHarvested: Long = 0L,
    val minEntropyRating: String = "CRYPTOGRAPHICALLY_SECURE_HARDWARE_BACKED",
    val primaryAlgorithm: String = "NIST SP 800-90A / HMAC-SHA512 + HKDF",
    val recentGeneratedNumbers: List<CsprngSampleRecord> = emptyList(),
    val waveformPoints: List<Float> = emptyList(), // Live physical sensor jitter waveform [-1.0f .. 1.0f]
    val csprngDiffusionWave: List<Float> = emptyList(), // Whitened CSPRNG diffusion amplitude [0.0f .. 1.0f]
    val shannonDispersionWave: List<Float> = emptyList(), // Shannon variance points [7.5f .. 8.0f]
    val peakJitterMicroG: Float = 384.6f,
    val noiseFloorDb: Float = -76.8f,
    val nyquistRateHz: Int = 120
)

/**
 * Individual record of a generated CSPRNG pseudo-random output
 */
data class CsprngSampleRecord(
    val id: String,
    val timestamp: Long = System.currentTimeMillis(),
    val randomHex: String,
    val randomIntUnsigned: Long,
    val randomFloatUnit: Float,
    val entropySource: String,
    val securityProtocolAssigned: String
)
